---
title: "SQANTI3 OUTPUT COMPARISON REPORT"
author: "`r paste0('  ','Author', ': ',Sys.getenv('USERNAME'))`"
date: "`r paste0('  ','Date', ': ', format(Sys.time(), '%d %B %Y'))`"
output:
  html_document:
    number_sections: false
    toc: false
    toc_float: false
    theme: spacelab
---

<!-- Basic setting -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, cache = FALSE, echo = FALSE)
venn <- FALSE
```

<!-- Run -->

```{r}
res <- compareTranscriptomes(f_in)
```

<!-- Summary generation -->

## Summary table

```{r}
str_cat <- c("antisense", "full-splice_match", "fusion", "genic", "incomplete-splice_match", "intergenic", "novel_in_catalog", "novel_not_in_catalog")
df_summary <- data.frame(ID = names(res[[2]][3:ncol(res[[2]])]))
n <- c()
for (i in res[[1]]) {
  n <- c(n, nrow(i))
}
df_summary$n_total <- n

for (i in str_cat) {
  n <- c()
  for (j in res[[1]]) {
    n <- c(n, nrow(j[j$structural_category == i,]))
  }
  df_summary[,i] <- n
}

DT::datatable(df_summary,
              extensions = "Buttons",
              options = list(
                  order = list(list(5, "asc"),list(1, "desc")),
                  dom = 'Bfrtip',
                  buttons = c('copy', 'csv', 'pdf', 'print')
              ),
              escape = FALSE,
              caption = "Table 1. Summary from SQANTI3 output comparison")
```

<!-- Plot generation -->

## Complete comparison {.tabset .tabset-pills}

<!-- Print or not Venn Diagrams -->

```{r}
if (length(f_in) < 4) {
  venn<-TRUE
  asis_output("### Venn Diagrams\\n") # Header
  }
```

```{r, eval=venn}
l <- list()
for (i in 3:ncol(res[[2]])){
  l[[i-2]] <- res[[2]][,i]
}
names(l) <- colnames(res[[2]])[3:ncol(res[[2]])]

print(ggvenn(
  l, 
  fill_color = c("#0073C2FF", "#EFC000FF", "#CD534CFF"),
  stroke_size = 0.5, set_name_size = 4
  ) + ggtitle("All isoforms") +
    theme(plot.title = element_text(hjust = 0.5)))
```

### UpSet plot

```{r}
l <- list()
for (i in 3:ncol(res[[2]])){
  l[[i-2]] <- res[[2]][,i]
}
names(l) <- colnames(res[[2]])[3:ncol(res[[2]])]

a <- UpSetR::upset(UpSetR::fromList(l), order.by = "freq", mainbar.y.label = "Isoform Intersections", sets.x.label = "Isoforms Per Sample")
print(a)
grid.text("All isoforms",x = 0.65, y=0.95, gp=gpar(fontsize=20))
```

### Standard deviation and Entropy

```{r}
a <- bind_rows(res$classifications, .id = "pipeline")
for (i in colnames(a[6:9])){
  print(ggplot(a, aes(log2(a[,i]))) +
  geom_density(aes(col = pipeline)) + xlab(paste0("log2(",i,")")))
}
```

<!-- By structural category -->

## Comparison by structural category

<!-- Print or not Venn Diagrams -->

```{r, results='asis'}
if (length(f_in) < 4) {
  venn<-TRUE
  cat("\n\n###  Venn Diagrams {.tabset .tabset-pills}\n") # Header
  }
```

```{r, eval=venn, results='asis'}
contador <- 1
for (i in 1:length(res[[2]])) {
  cat("\n\n#### ", str_cat[contador],"\n")
  
  a <- res[[2]][res[[2]]$structural_category == str_cat[i], names(res[[2]])[3:length(names(res[[2]]))]]
  l <- list()
  for (j in 1:ncol(a)) {
    l[[j]] <- na.omit(a[,j])
  }
  names(l) <- names(a)
  print(ggvenn(
  l, 
  fill_color = c("#0073C2FF", "#EFC000FF", "#CD534CFF"),
  stroke_size = 0.5, set_name_size = 4
  ) + ggtitle(str_cat[contador]) +
    theme(plot.title = element_text(hjust = 0.5)))
  contador <- contador + 1
}
```

### UpSet plot {.tabset .tabset-pills}

```{r, results='asis'}
for (i in 1:length(res[[2]])) {
  cat("\n\n#### ", str_cat[i],"\n")
  
  a <- res[[2]][res[[2]]$structural_category == str_cat[i], names(res[[2]])[3:length(names(res[[2]]))]]
  l <- list()
  for (j in 1:ncol(a)) {
    l[[j]] <- na.omit(a[,j])
  }
  names(l) <- names(a)
  
  a <- UpSetR::upset(UpSetR::fromList(l), order.by = "freq", mainbar.y.label = "Isoform Intersections", sets.x.label = "Isoforms Per Sample")
  print(a)
  grid.text(str_cat[i],x = 0.65, y=0.95, gp=gpar(fontsize=20))
}
```

## Presence/Ausence table

```{r}
DT::datatable(res[[3]],
              extensions = "Buttons",
              options = list(
                  order = list(list(5, "asc"),list(1, "desc")),
                  dom = 'Bfrtip',
                  buttons = c('copy', 'csv', 'pdf', 'print'),
                  pageLength = 10,
                  autoWidth = TRUE,
                  columnDefs = list(list(width = '100px', targets = "_all"))
              ),
              escape = FALSE,
              caption = "Table 1. Summary from SQANTI3 output comparison")
```

## SessionInfo

```{r}
sessionInfo()
```
